IMPROVEMENT: Add missing codeblock.
punktDe/neos-environment-display pull request #2
Opened 2021-07-08 08:40 UTC by crydotsnake

2021-08-03 00:36 UTC, simonschaufi requested changes

2021-08-03 00:36 UTC, simonschaufi commented on README.md
> +$ composer require punktde/neos-environment-display
remove dollar sign as it's not needed and should not be copied either.

2021-08-03 00:36 UTC, simonschaufi commented on README.md
> +$ composer require punktde/neos-environment-display
remove dollar sign as it's not needed and should not be copied either.

2021-08-03 00:45 UTC, simonschaufi requested changes

2021-08-03 00:45 UTC, simonschaufi commented on README.md
> +$ composer require punktde/neos-environment-display
```suggestion
composer require punktde/neos-environment-display
```

2021-08-03 00:46 UTC, simonschaufi requested changes
the dollar sign is not needed and should not be copied either

2021-08-04 14:09 UTC, crydotsnake commented
> the dollar sign is not needed and should not be copied either

Thank you ! :)

2022-05-07 21:53 UTC, closed without merging